package com.ademilsonmarsiglio.mailsender;

import com.google.gson.Gson;
import java.awt.Component;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import org.simplejavamail.mailer.config.TransportStrategy;

/**
 *
 * @author ademilsonmarsiglio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        cbxStrategy.setSelectedItem(TransportStrategy.SMTP_TLS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJsonParameters = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTemplateHTML = new javax.swing.JTextArea();
        pnlForm = new javax.swing.JPanel();
        btnSendMail = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSmtp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfPort = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfEmailFrom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfSubject = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxStrategy = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txfNameFrom = new javax.swing.JTextField();
        progress = new javax.swing.JProgressBar();
        txfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setResizeWeight(0.5);

        jLabel1.setText("Insert JSON parameter (name and mail is mandatory)");

        txtJsonParameters.setColumns(20);
        txtJsonParameters.setRows(5);
        txtJsonParameters.setText("[\n    {\"name\": \"Ademilson Marsiglio\", \"mail\": \"ademilson.marsiglio@gmail.com\", \"city\": \"Passo Fundo\", \"country\": \"Brazil\"},\n    {\"name\": \"Other Name\", \"mail\": \"ademilson.marsiglio@gmail.com\", \"city\": \"Passo Fundo\", \"country\": \"Brazil\"}\n]");
        jScrollPane1.setViewportView(txtJsonParameters);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 128, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel2.setText("Insert the TEMPLATE HTML (use ${nameOfParameter})");

        txtTemplateHTML.setColumns(20);
        txtTemplateHTML.setRows(5);
        txtTemplateHTML.setText("<html>\n\t<body>\n\t\t<span style=\"font-family: verdana, geneva, sans-serif; font-size: 14pt; color: #808080;\">\n            <strong>Hello ${name},</strong>\n        </span>\n        <br>\n        <br>\n        <div style=\"padding-left: 40px;\">\n            <span style=\"font-family: verdana, geneva, sans-serif; font-size: 12pt; color: #808080;\">\n                This is a mail test.\n                <br>\n            </span>\n        </div>\n        <br>\n        <br>\n        <div style=\"padding-left: 40px;\">\n            <span style=\"font-family: verdana, geneva, sans-serif; font-size: 12pt; color: #808080;\">\n                Show param test:\n                <br>\n                ${city} - ${contry}.\n            </span>\n        </div>\n        <br>\n        <div style=\"text-align: center;\">\n            <span style=\"font-family: verdana, geneva, sans-serif; font-size: 8pt; color: #808080;\">\n                Thank you for use my app.\n            </span>\n        </div>\n\t</body>\n</html>");
        jScrollPane2.setViewportView(txtTemplateHTML);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        btnSendMail.setText("Send e-mail");
        btnSendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMailActionPerformed(evt);
            }
        });

        jLabel3.setText("SMPT");

        txtSmtp.setText("smtp.gmail.com");
        txtSmtp.setName("SMTP"); // NOI18N

        jLabel4.setText("Port");

        txfPort.setColumns(5);
        txfPort.setText("587");
        txfPort.setName("Port"); // NOI18N

        jLabel5.setText("User");

        txfUser.setColumns(10);
        txfUser.setText("youruser");
        txfUser.setName("User"); // NOI18N

        jLabel6.setText("Password");

        txfEmailFrom.setText("youruser@gmail.com");
        txfEmailFrom.setName("Mail From"); // NOI18N

        jLabel7.setText("Mail from");

        txfSubject.setText("Dear ${name} from ${city} - ${country}... ");
        txfSubject.setName("Subject"); // NOI18N

        jLabel8.setText("Subject (use ${nameOfParameter} here too)");

        jLabel9.setText("Transport Strategy");

        cbxStrategy.setModel(new DefaultComboBoxModel(TransportStrategy.values()));

        jLabel10.setText("Name from");

        txfNameFrom.setColumns(10);
        txfNameFrom.setText("Your Name");
        txfNameFrom.setName("Name From"); // NOI18N

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txfEmailFrom, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFormLayout.createSequentialGroup()
                                        .addComponent(txtSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlFormLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(132, 132, 132)
                                        .addComponent(jLabel4))))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfNameFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addComponent(txfSubject)
                                .addGap(112, 112, 112))
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFormLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE))
                                    .addGroup(pnlFormLayout.createSequentialGroup()
                                        .addComponent(cbxStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendMail)))
                .addContainerGap())
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)))
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfEmailFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txfNameFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSendMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlForm, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMailActionPerformed
        new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                Mail mail = new Mail();
        
                enableAllComponents(false);
                progress.setIndeterminate(true);
                progress.setStringPainted(true);
                progress.setString("Validating data...");
                
                
                //validating
                for (Component component : pnlForm.getComponents()) {
                    try {
                        JTextField tf = (JTextField) component;
                        
                        if (component.getName() != null) {
                            if (tf.getText() == null || tf.getText().trim().isEmpty()) {
                                alert("Form Error", "Please, insert the " + component.getName() + " to continue.", JOptionPane.WARNING_MESSAGE);
                                component.requestFocus();
                                return Boolean.FALSE;
                            }
                        }
                    } catch(Exception e){}
                }
                
                
                try {    
                    mail.port = Integer.parseInt(txfPort.getText());
                    mail.smtp = txtSmtp.getText();
                    mail.fromEmail = txfEmailFrom.getText();
                    mail.fromName = txfNameFrom.getText();
                    mail.password = txfPassword.getText();
                    mail.strategy = (TransportStrategy) cbxStrategy.getSelectedItem();
                    mail.user = txfUser.getText();
                } catch (Exception e) {
                    Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Erro ao popular o objeto conforme o formulario.", e);
                    alert("Form Error", "Error to convert form data to object to send mail.", JOptionPane.ERROR_MESSAGE);
                    return Boolean.FALSE;
                }

                if (txtJsonParameters.getText().trim().isEmpty()) {
                    alert("JSON empty", "Please, insert the parameters JSON to continue.", JOptionPane.WARNING_MESSAGE);
                    return Boolean.FALSE;
                }

                if (txtTemplateHTML.getText().trim().isEmpty()) {
                    alert("HTML empty", "Please, insert the text or HTML to send mail.", JOptionPane.WARNING_MESSAGE);
                    return Boolean.FALSE;
                }

                HashMap[] parameters = new Gson().fromJson(txtJsonParameters.getText(), HashMap[].class);
                int countSuccess = 0;
                int failedSend = 0;
                int qtdNoInformationName = 0;
                int qtdNoInformationMail = 0;

                
                int limit = parameters.length;
                int i = 0;
                
                progress.setIndeterminate(false);
                progress.setMaximum(limit);
                
                
                
                for (HashMap param : parameters) {
                    
                    progress.setValue(i++);
                    progress.setString("send " + i + " of " + limit + "...");

                    if (!param.containsKey("name")) {
                        qtdNoInformationName++;
                        continue;
                    } 

                    if (!param.containsKey("mail")) {
                        qtdNoInformationMail++;
                        continue;
                    }

                    String htmlText = txtTemplateHTML.getText();
                    String subject = txfSubject.getText();

                    for (Object key : param.keySet()) {
                        htmlText = htmlText.replace("${" + key + "}", param.get(key).toString());
                        subject = subject.replace("${" + key + "}", param.get(key).toString());
                    }

                    if (mail.sendEmail(htmlText, param.get("name").toString(), param.get("mail").toString(), subject, false))
                        countSuccess++;
                    else 
                        failedSend++;
                }

                alert(
                    "Success"
                    , "Completed submission!!!\n\n"
                    + "(" + countSuccess + ") succes\n"
                    + "(" + failedSend + ") failed"
                    + (qtdNoInformationName > 0 ? "(" + qtdNoInformationName + ") no informating name" : "")
                    + (qtdNoInformationMail > 0 ? "(" + qtdNoInformationMail + ") no informating mail" : "")
                    , JOptionPane.INFORMATION_MESSAGE
                );
                
                return Boolean.TRUE;
            }

            @Override
            protected void done() {
                
                progress.setIndeterminate(false);
                progress.setString("");
                progress.setValue(0);
                enableAllComponents(true);
                
                super.done(); 
            }
            
            
        }.execute();
    }//GEN-LAST:event_btnSendMailActionPerformed

    
    private void alert(String title, String message, int type) {
        SwingUtilities.invokeLater(() -> {
            JOptionPane.showMessageDialog(this, message, title, type);
        });   
    }
    
    private void enableAllComponents(boolean enable) {
        txfEmailFrom.setEnabled(enable);
        txfNameFrom.setEnabled(enable);
        txfPassword.setEnabled(enable);
        txfPort.setEnabled(enable);
        txfSubject.setEnabled(enable);
        txfUser.setEnabled(enable);
        txtJsonParameters.setEnabled(enable);
        txtSmtp.setEnabled(enable);
        txtTemplateHTML.setEnabled(enable);
        cbxStrategy.setEnabled(enable);
        btnSendMail.setEnabled(enable);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main main = new Main();
                main.setTitle("VerySimple sender mail");
                main.setLocationRelativeTo(null);
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendMail;
    private javax.swing.JComboBox<String> cbxStrategy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JProgressBar progress;
    private javax.swing.JTextField txfEmailFrom;
    private javax.swing.JTextField txfNameFrom;
    private javax.swing.JPasswordField txfPassword;
    private javax.swing.JTextField txfPort;
    private javax.swing.JTextField txfSubject;
    private javax.swing.JTextField txfUser;
    private javax.swing.JTextArea txtJsonParameters;
    private javax.swing.JTextField txtSmtp;
    private javax.swing.JTextArea txtTemplateHTML;
    // End of variables declaration//GEN-END:variables
}
